/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paint.ui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author HaRy7x
 */
public class Canvas extends javax.swing.JPanel {

	BufferedImage mainImage;
	Graphics testG;

	/**
	 * Creates new form Canvas
	 */
	public Canvas() {
		initComponents();
		setup();
	}

	private void setup() {
		setSize(getPreferredSize());
		mainImage = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_RGB);
		testG = mainImage.createGraphics();
		testG.setColor(Color.white);
		testG.fillRect(0, 0, getWidth(), getHeight());
	}

	@Override
	public void paint(Graphics g) {
		System.out.println("Paint Component");
		super.paintComponent(g);
//			g.setColor(getBackground());
		g.drawImage(mainImage, 0, 0, null);
	}

	public void setMainImage(BufferedImage image) {
		mainImage = image;
		image.flush();
		System.gc();
		repaint();
	}

	public BufferedImage getMainImage() {
		return mainImage;
	}

	public BufferedImage getMainImageCopy() {
		return getImageCopy(mainImage);
	}

	public BufferedImage getImageCopy(BufferedImage image) {
		BufferedImage temp = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_RGB);
		Graphics2D g2d = temp.createGraphics();
		g2d.drawImage(image, null, 0, 0);
		return temp;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(689, 430));
        setMinimumSize(new java.awt.Dimension(689, 430));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(689, 430));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}