/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paint.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;

/**
 *
 * @author HaRy7x
 */
public class Canvas extends javax.swing.JPanel implements Printable {

	private BufferedImage mainImage;
	private Graphics mainGraphics;

	/**
	 * Creates new form Canvas
	 */
	public Canvas() {
		initComponents();
		setup();
	}

	public final void setup() {
		setSize(getPreferredSize());
		Dimension maxSize = getMaximumSize();
		mainImage = new BufferedImage(maxSize.width, maxSize.height, BufferedImage.TYPE_INT_RGB);
		mainGraphics = mainImage.createGraphics();
		mainGraphics.setColor(Color.white);
		mainGraphics.fillRect(0, 0, getWidth(), getHeight());
	}

	@Override
	public void paint(Graphics g) {
		super.paintComponent(g);
		g.drawImage(mainImage, 0, 0, null);
	}

	public void setMainImage(BufferedImage image) {
		mainImage = image;
		image.flush();
		System.gc();
		repaint();
	}

	public BufferedImage getMainImage() {
		return mainImage;
	}

	public BufferedImage getMainImageCopy() {
		return getImageCopy(mainImage);
	}

	public BufferedImage getImageCopy(BufferedImage image) {
		BufferedImage temp = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_RGB);
		Graphics2D g2d = temp.createGraphics();
		g2d.drawImage(image, null, 0, 0);
		return temp;
	}

	public void setMainGraphics(Graphics g) {
		this.mainGraphics = g;
	}

	public Graphics getMainGraphics() {
		return this.mainGraphics;
	}

	@Override
	public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
		Graphics2D g2d = (Graphics2D) graphics;
		graphics.translate((int) (pageFormat.getImageableX()), (int) (pageFormat.getImageableY()));
		if (pageIndex == 0) {
			double pageWidth = pageFormat.getImageableWidth();
			double pageHeight = pageFormat.getImageableHeight();
			double imageWidth = mainImage.getWidth();
			double imageHeight = mainImage.getHeight();
			double scaleX = pageWidth / imageWidth;
			double scaleY = pageHeight / imageHeight;
			double scaleFactor = Math.min(scaleX, scaleY);
			g2d.scale(scaleFactor, scaleFactor);
			graphics.drawImage(mainImage, 0, 0, null);
			return Printable.PAGE_EXISTS;
		}
		return Printable.NO_SUCH_PAGE;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(1800, 1000));
        setMinimumSize(new java.awt.Dimension(1800, 1000));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1800, 1000));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}