/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paint.ui;

import java.awt.Color;
import java.awt.Point;
import java.util.LinkedList;
import java.util.List;
import paint.shape.LineBressenham;
import paint.shape.MidpointCircle;
import paint.shape.MidpointEllipse;
import paint.shape.Shape2D;

/**
 *
 * @author HaRy7x
 */
public class MainWindow extends javax.swing.JFrame {

	private boolean hasBeenSaved;

	private Point startPoint;
	private Point endPoint;

	private List<Shape2D> drawedShapes = new LinkedList<Shape2D>();

	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shapeButtonGroup = new javax.swing.ButtonGroup();
        container = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        shapePanel = new javax.swing.JPanel();
        btnLineDDA = new javax.swing.JToggleButton();
        btnBressenham = new javax.swing.JToggleButton();
        btnMidpointCircle = new javax.swing.JToggleButton();
        btnMidpointEllipse = new javax.swing.JToggleButton();
        btnRectangle = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        canvas = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        lbCursor = new javax.swing.JLabel();
        lbCursorPosition = new javax.swing.JLabel();
        lbStart = new javax.swing.JLabel();
        lbStartPosition = new javax.swing.JLabel();
        lbEnd = new javax.swing.JLabel();
        lbEndPosition = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cemungudh Paint");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(805, 505));
        setMinimumSize(new java.awt.Dimension(805, 505));
        setPreferredSize(new java.awt.Dimension(805, 505));
        setResizable(false);

        mainPanel.setPreferredSize(new java.awt.Dimension(800, 450));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.LINE_AXIS));

        sidePanel.setMaximumSize(new java.awt.Dimension(110, 32767));
        sidePanel.setMinimumSize(new java.awt.Dimension(110, 100));

        shapePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Shapes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        shapePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shapePanel.setFocusable(false);
        shapePanel.setMaximumSize(new java.awt.Dimension(110, 160));
        shapePanel.setMinimumSize(new java.awt.Dimension(110, 160));
        shapePanel.setPreferredSize(new java.awt.Dimension(110, 160));
        shapePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shapeButtonGroup.add(btnLineDDA);
        btnLineDDA.setText("Line");
        btnLineDDA.setToolTipText("DDA Algorithm");
        btnLineDDA.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLineDDA.setFocusPainted(false);
        btnLineDDA.setFocusable(false);
        btnLineDDA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLineDDA.setMaximumSize(new java.awt.Dimension(30, 30));
        btnLineDDA.setMinimumSize(new java.awt.Dimension(30, 30));
        btnLineDDA.setPreferredSize(new java.awt.Dimension(30, 30));
        btnLineDDA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        shapePanel.add(btnLineDDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        shapeButtonGroup.add(btnBressenham);
        btnBressenham.setText("Line");
        btnBressenham.setToolTipText("Bressenham Algorithm");
        btnBressenham.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBressenham.setFocusPainted(false);
        btnBressenham.setFocusable(false);
        btnBressenham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBressenham.setMaximumSize(new java.awt.Dimension(25, 25));
        btnBressenham.setMinimumSize(new java.awt.Dimension(25, 25));
        btnBressenham.setPreferredSize(new java.awt.Dimension(26, 26));
        btnBressenham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        shapePanel.add(btnBressenham, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 30, 30));

        shapeButtonGroup.add(btnMidpointCircle);
        btnMidpointCircle.setText("Circle");
        btnMidpointCircle.setToolTipText("Midpoint Circle Algorithm");
        btnMidpointCircle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMidpointCircle.setFocusPainted(false);
        btnMidpointCircle.setFocusable(false);
        btnMidpointCircle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMidpointCircle.setMaximumSize(new java.awt.Dimension(30, 30));
        btnMidpointCircle.setMinimumSize(new java.awt.Dimension(30, 30));
        btnMidpointCircle.setPreferredSize(new java.awt.Dimension(30, 30));
        btnMidpointCircle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        shapePanel.add(btnMidpointCircle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 30, 30));

        shapeButtonGroup.add(btnMidpointEllipse);
        btnMidpointEllipse.setText("Ellipse");
        btnMidpointEllipse.setToolTipText("Midpoint Ellipse Algorithm");
        btnMidpointEllipse.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMidpointEllipse.setFocusPainted(false);
        btnMidpointEllipse.setFocusable(false);
        btnMidpointEllipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMidpointEllipse.setPreferredSize(new java.awt.Dimension(26, 26));
        btnMidpointEllipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        shapePanel.add(btnMidpointEllipse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 30, 30));

        shapeButtonGroup.add(btnRectangle);
        btnRectangle.setText("Rectangle");
        btnRectangle.setToolTipText("Rectangle");
        btnRectangle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRectangle.setFocusPainted(false);
        btnRectangle.setFocusable(false);
        btnRectangle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRectangle.setPreferredSize(new java.awt.Dimension(26, 26));
        btnRectangle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        shapePanel.add(btnRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 30, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shapePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(shapePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 114, Short.MAX_VALUE))
        );

        mainPanel.add(sidePanel);

        canvas.setBackground(new java.awt.Color(255, 255, 255));
        canvas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        canvas.setAlignmentX(0.6F);
        canvas.setAlignmentY(0.6F);
        canvas.setMaximumSize(new java.awt.Dimension(689, 32767));
        canvas.setMinimumSize(new java.awt.Dimension(689, 0));
        canvas.setPreferredSize(new java.awt.Dimension(689, 430));
        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canvasMouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                canvasMousePressed(evt);
            }
        });
        canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canvasMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                canvasMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        mainPanel.add(canvas);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bottomPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbCursor.setText("Cursor : ");
        lbCursor.setMaximumSize(new java.awt.Dimension(45, 16));
        lbCursor.setMinimumSize(new java.awt.Dimension(45, 16));
        lbCursor.setPreferredSize(new java.awt.Dimension(45, 16));

        lbCursorPosition.setText("-");

        lbStart.setText("Start Point :");

        lbStartPosition.setText("-");

        lbEnd.setText("End Point : ");

        lbEndPosition.setText("-");

        jLabel1.setText("Copyright by : Haryanto M.Rizal, Neng Mira Rahayu, Arvina Yulia");

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbCursor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbCursorPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbStart, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbStartPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbEnd)
                .addGap(0, 0, 0)
                .addComponent(lbEndPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCursor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCursorPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbStart)
                    .addComponent(lbStartPosition)
                    .addComponent(lbEnd)
                    .addComponent(lbEndPosition)
                    .addComponent(jLabel1)))
        );

        menuFile.setText("File");

        menuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        menuFile.add(menuNew);

        menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOpen.setText("Open");
        menuFile.add(menuOpen);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setText("Save");
        menuFile.add(menuSave);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        menuBar.add(menuFile);

        menuHelp.setText("Help");

        menuAbout.setText("jMenuItem5");
        menuHelp.add(menuAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canvasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseMoved
		lbCursorPosition.setText("[" + evt.getX() + "," + evt.getY() + "]");
    }//GEN-LAST:event_canvasMouseMoved

    private void canvasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMousePressed
		startPoint = new Point(evt.getX(), evt.getY());
		lbStartPosition.setText("[" + evt.getX() + "," + evt.getY() + "]");
    }//GEN-LAST:event_canvasMousePressed

    private void canvasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseReleased
		endPoint = new Point(evt.getX(), evt.getY());
		lbEndPosition.setText("[" + evt.getX() + "," + evt.getY() + "]");

//		Do nothing if no shape button selected
		if (shapeButtonGroup.getSelection() == null) return;

		int lineSize = 1;
		Color shapeColor = Color.RED;

		int borderSize = 1;
		Color borderColor = Color.RED;

		Shape2D newShape = null;

		if (btnBressenham.isSelected()) {
			newShape = new LineBressenham(startPoint, endPoint, lineSize, shapeColor);
		} else if (btnLineDDA.isSelected()) {
			newShape = new LineBressenham(startPoint, endPoint, lineSize, shapeColor);
		} else if (btnMidpointCircle.isSelected()) {
			newShape = new MidpointCircle(startPoint, endPoint, lineSize, shapeColor, borderSize, borderColor);
		} else if (btnMidpointEllipse.isSelected()) {
			newShape = new MidpointEllipse(startPoint, endPoint, lineSize, shapeColor, borderSize, borderColor);
		} else if (btnRectangle.isSelected()) {
		}

		drawedShapes.add(newShape);
		newShape.draw(canvas.getGraphics());

		hasBeenSaved = false;
    }//GEN-LAST:event_canvasMouseReleased

    private void canvasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseDragged
		lbCursorPosition.setText("[" + evt.getX() + "," + evt.getY() + "]");
    }//GEN-LAST:event_canvasMouseDragged

    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
		canvas.update(canvas.getGraphics());
    }//GEN-LAST:event_menuNewActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
		dispose();
    }//GEN-LAST:event_menuExitActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JToggleButton btnBressenham;
    private javax.swing.JToggleButton btnLineDDA;
    private javax.swing.JToggleButton btnMidpointCircle;
    private javax.swing.JToggleButton btnMidpointEllipse;
    private javax.swing.JToggleButton btnRectangle;
    private javax.swing.JPanel canvas;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbCursor;
    private javax.swing.JLabel lbCursorPosition;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbEndPosition;
    private javax.swing.JLabel lbStart;
    private javax.swing.JLabel lbStartPosition;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.ButtonGroup shapeButtonGroup;
    private javax.swing.JPanel shapePanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
