/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paint.ui;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import paint.shape.LineStyle;
import paint.shape.MaskedLine;
import paint.shape.SolidLine;
import paint.tool.BrushTool;
import paint.tool.CircleTool;
import paint.tool.ColorPicker;
import paint.tool.EllipseTool;
import paint.tool.FloodFillTool;
import paint.tool.LineBressenhamTool;
import paint.tool.LineDDATool;
import paint.tool.Tool;

/**
 *
 * @author HaRy7x
 */
public class Paint extends javax.swing.JFrame {

	private String projectName = "new-painting";
	private boolean hasBeenSaved;

	Tool selectedTool;

	/**
	 * Creates new form Paint
	 */
	public Paint() {
		initComponents();
		setupCanvas();
	}

	private void setupCanvas() {
		Canvas canvas = getCanvas();
		canvas.setSize(canvas.getPreferredSize());
		canvas.setMainImage(new BufferedImage(canvas.getWidth(), canvas.getHeight(), BufferedImage.TYPE_INT_RGB));
		canvas.setMainGraphics(canvas.getMainImage().createGraphics());
		canvas.getMainGraphics().setColor(Color.WHITE);
		canvas.getMainGraphics().fillRect(0, 0, canvas.getWidth(), canvas.getHeight());
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shapeButtonGroup = new javax.swing.ButtonGroup();
        containerPane = new javax.swing.JPanel();
        mainPane = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        shapePane = new javax.swing.JPanel();
        btnLineDDA = new javax.swing.JToggleButton();
        btnBressenham = new javax.swing.JToggleButton();
        btnMidpointCircle = new javax.swing.JToggleButton();
        btnMidpointEllipse = new javax.swing.JToggleButton();
        btnRectangle = new javax.swing.JToggleButton();
        btnFloodFill = new javax.swing.JToggleButton();
        btnBrush = new javax.swing.JToggleButton();
        btnColorPicker = new javax.swing.JToggleButton();
        colorPane = new javax.swing.JPanel();
        color1Wrapper = new javax.swing.JPanel();
        color1 = new javax.swing.JPanel();
        lblColor1 = new javax.swing.JLabel();
        color2Wrapper = new javax.swing.JPanel();
        color2 = new javax.swing.JPanel();
        lblColor2 = new javax.swing.JLabel();
        lineStylePane = new javax.swing.JPanel();
        cmbLineStyle = new javax.swing.JComboBox();
        fillStylePane = new javax.swing.JPanel();
        cmbFillStyle = new javax.swing.JComboBox();
        pixelPane = new javax.swing.JPanel();
        pixelSlider = new javax.swing.JSlider();
        canvas = new paint.ui.Canvas();
        bottomPane = new javax.swing.JPanel();
        lbCursor = new javax.swing.JLabel();
        lbCursorPosition = new javax.swing.JLabel();
        lbStart = new javax.swing.JLabel();
        lbStartPosition = new javax.swing.JLabel();
        lbEnd = new javax.swing.JLabel();
        lbEndPosition = new javax.swing.JLabel();
        lbCopyright = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuSaveAs = new javax.swing.JMenuItem();
        menuPrint = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cemungudh Paint");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1800, 1000));
        setMinimumSize(new java.awt.Dimension(810, 550));
        setName("PaintFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(810, 550));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        containerPane.setMaximumSize(new java.awt.Dimension(1800, 1000));
        containerPane.setMinimumSize(new java.awt.Dimension(810, 500));
        containerPane.setPreferredSize(new java.awt.Dimension(810, 500));
        containerPane.setLayout(new javax.swing.BoxLayout(containerPane, javax.swing.BoxLayout.PAGE_AXIS));

        mainPane.setFocusable(false);
        mainPane.setMaximumSize(new java.awt.Dimension(1800, 1000));
        mainPane.setMinimumSize(new java.awt.Dimension(800, 450));
        mainPane.setPreferredSize(new java.awt.Dimension(800, 450));
        mainPane.setLayout(new javax.swing.BoxLayout(mainPane, javax.swing.BoxLayout.LINE_AXIS));

        sidePane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sidePane.setMaximumSize(new java.awt.Dimension(112, 1000));
        sidePane.setMinimumSize(new java.awt.Dimension(112, 1000));
        sidePane.setPreferredSize(new java.awt.Dimension(112, 1000));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shapePane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Shapes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11))); // NOI18N
        shapePane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shapePane.setDoubleBuffered(false);
        shapePane.setFocusable(false);
        shapePane.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        shapePane.setMaximumSize(new java.awt.Dimension(2000, 212));
        shapePane.setMinimumSize(new java.awt.Dimension(2000, 212));
        shapePane.setName(""); // NOI18N
        shapePane.setPreferredSize(new java.awt.Dimension(2000, 212));
        shapePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shapeButtonGroup.add(btnLineDDA);
        btnLineDDA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnLineDDA.setText("Line");
        btnLineDDA.setToolTipText("DDA Algorithm");
        btnLineDDA.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLineDDA.setFocusPainted(false);
        btnLineDDA.setFocusable(false);
        btnLineDDA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLineDDA.setMaximumSize(new java.awt.Dimension(30, 30));
        btnLineDDA.setMinimumSize(new java.awt.Dimension(30, 30));
        btnLineDDA.setPreferredSize(new java.awt.Dimension(30, 30));
        btnLineDDA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLineDDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineDDAActionPerformed(evt);
            }
        });
        shapePane.add(btnLineDDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        shapeButtonGroup.add(btnBressenham);
        btnBressenham.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnBressenham.setText("Line");
        btnBressenham.setToolTipText("Bressenham Algorithm");
        btnBressenham.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBressenham.setFocusPainted(false);
        btnBressenham.setFocusable(false);
        btnBressenham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBressenham.setMaximumSize(new java.awt.Dimension(25, 25));
        btnBressenham.setMinimumSize(new java.awt.Dimension(25, 25));
        btnBressenham.setPreferredSize(new java.awt.Dimension(26, 26));
        btnBressenham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBressenham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBressenhamActionPerformed(evt);
            }
        });
        shapePane.add(btnBressenham, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 30, 30));

        shapeButtonGroup.add(btnMidpointCircle);
        btnMidpointCircle.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnMidpointCircle.setText("Circle");
        btnMidpointCircle.setToolTipText("Midpoint Circle Algorithm");
        btnMidpointCircle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMidpointCircle.setFocusPainted(false);
        btnMidpointCircle.setFocusable(false);
        btnMidpointCircle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMidpointCircle.setMaximumSize(new java.awt.Dimension(30, 30));
        btnMidpointCircle.setMinimumSize(new java.awt.Dimension(30, 30));
        btnMidpointCircle.setPreferredSize(new java.awt.Dimension(30, 30));
        btnMidpointCircle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMidpointCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMidpointCircleActionPerformed(evt);
            }
        });
        shapePane.add(btnMidpointCircle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 30, 30));

        shapeButtonGroup.add(btnMidpointEllipse);
        btnMidpointEllipse.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnMidpointEllipse.setText("Ellipse");
        btnMidpointEllipse.setToolTipText("Midpoint Ellipse Algorithm");
        btnMidpointEllipse.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMidpointEllipse.setFocusPainted(false);
        btnMidpointEllipse.setFocusable(false);
        btnMidpointEllipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMidpointEllipse.setPreferredSize(new java.awt.Dimension(26, 26));
        btnMidpointEllipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMidpointEllipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMidpointEllipseActionPerformed(evt);
            }
        });
        shapePane.add(btnMidpointEllipse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 30, 30));

        shapeButtonGroup.add(btnRectangle);
        btnRectangle.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnRectangle.setText("Rectangle");
        btnRectangle.setToolTipText("Rectangle");
        btnRectangle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRectangle.setFocusPainted(false);
        btnRectangle.setFocusable(false);
        btnRectangle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRectangle.setPreferredSize(new java.awt.Dimension(26, 26));
        btnRectangle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangleActionPerformed(evt);
            }
        });
        shapePane.add(btnRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 30, 30));

        shapeButtonGroup.add(btnFloodFill);
        btnFloodFill.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnFloodFill.setText("Fill");
        btnFloodFill.setToolTipText("Flood Fill");
        btnFloodFill.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFloodFill.setFocusPainted(false);
        btnFloodFill.setMaximumSize(new java.awt.Dimension(25, 25));
        btnFloodFill.setMinimumSize(new java.awt.Dimension(25, 25));
        btnFloodFill.setPreferredSize(new java.awt.Dimension(25, 25));
        btnFloodFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloodFillActionPerformed(evt);
            }
        });
        shapePane.add(btnFloodFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, 30));

        shapeButtonGroup.add(btnBrush);
        btnBrush.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnBrush.setText("Brush");
        btnBrush.setToolTipText("Brush Tool");
        btnBrush.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBrush.setFocusPainted(false);
        btnBrush.setFocusable(false);
        btnBrush.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBrush.setMaximumSize(new java.awt.Dimension(30, 30));
        btnBrush.setMinimumSize(new java.awt.Dimension(30, 30));
        btnBrush.setPreferredSize(new java.awt.Dimension(30, 30));
        btnBrush.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBrush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrushActionPerformed(evt);
            }
        });
        shapePane.add(btnBrush, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 30, 30));

        shapeButtonGroup.add(btnColorPicker);
        btnColorPicker.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnColorPicker.setText("Picker");
        btnColorPicker.setToolTipText("Color Picker");
        btnColorPicker.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnColorPicker.setFocusPainted(false);
        btnColorPicker.setMaximumSize(new java.awt.Dimension(25, 25));
        btnColorPicker.setMinimumSize(new java.awt.Dimension(25, 25));
        btnColorPicker.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColorPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorPickerActionPerformed(evt);
            }
        });
        shapePane.add(btnColorPicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 30, 30));

        sidePane.add(shapePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 130));

        colorPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11))); // NOI18N
        colorPane.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        colorPane.setMaximumSize(new java.awt.Dimension(220, 32767));
        colorPane.setMinimumSize(new java.awt.Dimension(220, 0));
        colorPane.setPreferredSize(new java.awt.Dimension(220, 242));
        colorPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        color1Wrapper.setPreferredSize(new java.awt.Dimension(54, 81));

        color1.setBackground(new java.awt.Color(124, 211, 211));
        color1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        color1.setPreferredSize(new java.awt.Dimension(30, 30));
        color1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                color1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                color1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout color1Layout = new javax.swing.GroupLayout(color1);
        color1.setLayout(color1Layout);
        color1Layout.setHorizontalGroup(
            color1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        color1Layout.setVerticalGroup(
            color1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        lblColor1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblColor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColor1.setText("Color 1");

        javax.swing.GroupLayout color1WrapperLayout = new javax.swing.GroupLayout(color1Wrapper);
        color1Wrapper.setLayout(color1WrapperLayout);
        color1WrapperLayout.setHorizontalGroup(
            color1WrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(color1WrapperLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(color1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblColor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        color1WrapperLayout.setVerticalGroup(
            color1WrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(color1WrapperLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(color1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblColor1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        colorPane.add(color1Wrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 48, 60));

        color2.setBackground(new java.awt.Color(168, 163, 251));
        color2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        color2.setPreferredSize(new java.awt.Dimension(30, 30));
        color2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                color2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                color2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout color2Layout = new javax.swing.GroupLayout(color2);
        color2.setLayout(color2Layout);
        color2Layout.setHorizontalGroup(
            color2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        color2Layout.setVerticalGroup(
            color2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        lblColor2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblColor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColor2.setText("Color 2");
        lblColor2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout color2WrapperLayout = new javax.swing.GroupLayout(color2Wrapper);
        color2Wrapper.setLayout(color2WrapperLayout);
        color2WrapperLayout.setHorizontalGroup(
            color2WrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(color2WrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(color2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblColor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        color2WrapperLayout.setVerticalGroup(
            color2WrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(color2WrapperLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(color2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblColor2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        colorPane.add(color2Wrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 16, -1, 60));

        sidePane.add(colorPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 110, 80));

        lineStylePane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Line Style", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11))); // NOI18N
        lineStylePane.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lineStylePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbLineStyle.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmbLineStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solid", "Dashed", "Dotted" }));
        cmbLineStyle.setToolTipText(cmbLineStyle.getName());
        cmbLineStyle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbLineStyle.setRequestFocusEnabled(false);
        lineStylePane.add(cmbLineStyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        sidePane.add(lineStylePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 110, 60));

        fillStylePane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fill Style", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11))); // NOI18N
        fillStylePane.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fillStylePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbFillStyle.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmbFillStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hollow", "Fill", "Bordered", "Pattern" }));
        cmbFillStyle.setToolTipText("");
        cmbFillStyle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbFillStyle.setRequestFocusEnabled(false);
        fillStylePane.add(cmbFillStyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        sidePane.add(fillStylePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 110, 60));

        pixelPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Line Width", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11))); // NOI18N
        pixelPane.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pixelPane.setInheritsPopupMenu(true);
        pixelPane.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                pixelPaneMouseWheelMoved(evt);
            }
        });
        pixelPane.setLayout(new javax.swing.BoxLayout(pixelPane, javax.swing.BoxLayout.LINE_AXIS));

        pixelSlider.setMaximum(50);
        pixelSlider.setMinimum(2);
        pixelSlider.setPaintTicks(true);
        pixelSlider.setSnapToTicks(true);
        pixelSlider.setValue(2);
        pixelSlider.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                pixelSliderMouseWheelMoved(evt);
            }
        });
        pixelSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pixelSliderMouseEntered(evt);
            }
        });
        pixelSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pixelSliderMouseDragged(evt);
            }
        });
        pixelPane.add(pixelSlider);

        sidePane.add(pixelPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 110, 50));

        mainPane.add(sidePane);

        canvas.setBackground(new java.awt.Color(255, 255, 255));
        canvas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        canvas.setToolTipText(""); // NOI18N
        canvas.setAlignmentX(0.0F);
        canvas.setAlignmentY(0.0F);
        canvas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        canvas.setFocusable(false);
        canvas.setMaximumSize(new java.awt.Dimension(1800, 1000));
        canvas.setMinimumSize(new java.awt.Dimension(1800, 1000));
        canvas.setName(""); // NOI18N
        canvas.setPreferredSize(new java.awt.Dimension(1800, 1000));
        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                canvasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canvasMouseReleased(evt);
            }
        });
        canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                canvasMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canvasMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1796, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );

        mainPane.add(canvas);

        containerPane.add(mainPane);

        bottomPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bottomPane.setMaximumSize(new java.awt.Dimension(1800, 20));

        lbCursor.setText("Cursor : ");
        lbCursor.setMaximumSize(new java.awt.Dimension(45, 16));
        lbCursor.setMinimumSize(new java.awt.Dimension(45, 16));
        lbCursor.setPreferredSize(new java.awt.Dimension(45, 16));

        lbCursorPosition.setText("-");

        lbStart.setText("Start Point :");

        lbStartPosition.setText("-");

        lbEnd.setText("End Point : ");

        lbEndPosition.setText("-");

        lbCopyright.setText("Copyright by : Haryanto M.Rizal, Neng Mira Rahayu, Arvina Yulia");

        javax.swing.GroupLayout bottomPaneLayout = new javax.swing.GroupLayout(bottomPane);
        bottomPane.setLayout(bottomPaneLayout);
        bottomPaneLayout.setHorizontalGroup(
            bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPaneLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbCursor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbCursorPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbStart, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbStartPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbEnd)
                .addGap(0, 0, 0)
                .addComponent(lbEndPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(lbCopyright)
                .addContainerGap())
        );
        bottomPaneLayout.setVerticalGroup(
            bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCursor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCursorPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbStart)
                    .addComponent(lbStartPosition)
                    .addComponent(lbEnd)
                    .addComponent(lbEndPosition)
                    .addComponent(lbCopyright)))
        );

        containerPane.add(bottomPane);

        getContentPane().add(containerPane);

        menuBar.setBackground(new java.awt.Color(153, 153, 153));

        menuFile.setText("File");
        menuFile.setMargin(new java.awt.Insets(0, 6, 0, 6));

        menuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNew.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        menuFile.add(menuNew);

        menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOpen.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        menuOpen.setText("Open");
        menuFile.add(menuOpen);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        menuSave.setText("Save");
        menuFile.add(menuSave);

        menuSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuSaveAs.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        menuSaveAs.setText("Save As");
        menuFile.add(menuSaveAs);

        menuPrint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuPrint.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        menuPrint.setText("Print");
        menuPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrintActionPerformed(evt);
            }
        });
        menuFile.add(menuPrint);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        menuBar.add(menuFile);

        menuEdit.setText("Edit");
        menuEdit.setMargin(new java.awt.Insets(0, 6, 0, 6));
        menuBar.add(menuEdit);

        menuHelp.setText("Help");
        menuHelp.setMargin(new java.awt.Insets(0, 5, 0, 5));

        menuAbout.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        menuAbout.setText("About");
        menuHelp.add(menuAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(826, 534));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	public Canvas getCanvas() {
		return (Canvas) canvas;
	}

	public LineStyle getLineStyle() {
		if ("Dashed".equals((String) cmbLineStyle.getSelectedItem())) {
			return new MaskedLine(pixelSlider.getValue(), 5, 3);
		} else if ("Dotted".equals((String) cmbLineStyle.getSelectedItem())) {
			return new MaskedLine(pixelSlider.getValue(), 1, 3);
		} else {
			return new SolidLine();
		}
	}

    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
		getCanvas().setup();
		getCanvas().repaint();
    }//GEN-LAST:event_menuNewActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
		dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    private void canvasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseDragged
		lbCursorPosition.setText("[" + evt.getX() + "," + evt.getY() + "]");
		if (selectedTool != null) {
			selectedTool.actionMouseDragged(evt, getCanvas());
		}
    }//GEN-LAST:event_canvasMouseDragged

    private void canvasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseMoved
		lbCursorPosition.setText("[" + evt.getX() + "," + evt.getY() + "]");
    }//GEN-LAST:event_canvasMouseMoved

    private void canvasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseReleased
		lbEndPosition.setText("[" + evt.getX() + "," + evt.getY() + "]");
		if (selectedTool != null) {
			selectedTool.actionMouseReleased(evt, getCanvas());
		}
    }//GEN-LAST:event_canvasMouseReleased

    private void canvasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMousePressed
		lbStartPosition.setText("[" + evt.getX() + "," + evt.getY() + "]");
		lbEndPosition.setText("[" + evt.getX() + "," + evt.getY() + "]");
		if (selectedTool != null) {
			selectedTool.actionMouseClicked(evt, getCanvas());
		}
    }//GEN-LAST:event_canvasMousePressed

    private void pixelSliderMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_pixelSliderMouseWheelMoved
		int newVal = pixelSlider.getValue() - evt.getUnitsToScroll();
		pixelSlider.setValue(newVal);
		pixelSlider.setToolTipText(pixelSlider.getValue() + " pixel");
    }//GEN-LAST:event_pixelSliderMouseWheelMoved

    private void pixelPaneMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_pixelPaneMouseWheelMoved
		int newVal = pixelSlider.getValue() - evt.getUnitsToScroll();
		pixelSlider.setValue(newVal);
		pixelSlider.setToolTipText(pixelSlider.getValue() + " pixel");
    }//GEN-LAST:event_pixelPaneMouseWheelMoved

    private void color1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_color1MouseEntered
		Color color = color1.getBackground();
		color1.setToolTipText("RGB={" + color.getRed() + "," + color.getGreen() + "," + color.getBlue() + "}");
    }//GEN-LAST:event_color1MouseEntered

    private void color2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_color2MouseEntered
		Color color = color2.getBackground();
		color2.setToolTipText("RGB={" + color.getRed() + "," + color.getGreen() + "," + color.getBlue() + "}");
    }//GEN-LAST:event_color2MouseEntered

    private void pixelSliderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pixelSliderMouseEntered
		pixelSlider.setToolTipText(pixelSlider.getValue() + " pixel");
    }//GEN-LAST:event_pixelSliderMouseEntered

    private void pixelSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pixelSliderMouseDragged
		pixelSlider.setToolTipText(pixelSlider.getValue() + " pixel");
    }//GEN-LAST:event_pixelSliderMouseDragged

    private void btnMidpointEllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMidpointEllipseActionPerformed
		if (!(selectedTool instanceof EllipseTool)) {
			selectedTool = new EllipseTool(this);
		}
    }//GEN-LAST:event_btnMidpointEllipseActionPerformed

    private void btnMidpointCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMidpointCircleActionPerformed
		if (!(selectedTool instanceof CircleTool)) {
			selectedTool = new CircleTool(this);
		}
    }//GEN-LAST:event_btnMidpointCircleActionPerformed

    private void btnLineDDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineDDAActionPerformed
		if (!(selectedTool instanceof LineDDATool)) {
			selectedTool = new LineDDATool(this);
		}
    }//GEN-LAST:event_btnLineDDAActionPerformed

    private void btnBressenhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBressenhamActionPerformed
		if (!(selectedTool instanceof LineBressenhamTool)) {
			selectedTool = new LineBressenhamTool(this);
		}
    }//GEN-LAST:event_btnBressenhamActionPerformed

    private void color1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_color1MousePressed
		Color color = JColorChooser.showDialog(this, "Choose Color 1", color1.getBackground());
		if (color == null) {
			return;
		}
		color1.setBackground(color);
		color1.setToolTipText("RGB={" + color.getRed() + "," + color.getGreen() + "," + color.getBlue() + "}");
    }//GEN-LAST:event_color1MousePressed

    private void color2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_color2MousePressed
		Color color = JColorChooser.showDialog(this, "Choose Color 2", color2.getBackground());
		if (color == null) {
			return;
		}
		color2.setBackground(color);
		color2.setToolTipText("RGB={" + color.getRed() + "," + color.getGreen() + "," + color.getBlue() + "}");
    }//GEN-LAST:event_color2MousePressed

    private void btnFloodFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloodFillActionPerformed
		if (!(selectedTool instanceof FloodFillTool)) {
			selectedTool = new FloodFillTool(this);
		}
    }//GEN-LAST:event_btnFloodFillActionPerformed

    private void btnBrushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrushActionPerformed
		if (!(selectedTool instanceof BrushTool)) {
			selectedTool = new BrushTool(this);
		}
    }//GEN-LAST:event_btnBrushActionPerformed

    private void btnRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangleActionPerformed
		selectedTool = null;
    }//GEN-LAST:event_btnRectangleActionPerformed

    private void btnColorPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorPickerActionPerformed
		if (!(selectedTool instanceof ColorPicker)) {
			selectedTool = new ColorPicker(this);
		}
    }//GEN-LAST:event_btnColorPickerActionPerformed

    private void menuPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrintActionPerformed
		PrinterJob job = PrinterJob.getPrinterJob();
		job.setJobName(projectName);
		job.setPrintable(getCanvas());
		if (job.printDialog()) {
			try {
				job.print();
			} catch (PrinterException ex) {
				JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Print Error", JOptionPane.ERROR_MESSAGE);
			}
		}
    }//GEN-LAST:event_menuPrintActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Paint().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bottomPane;
    private javax.swing.JToggleButton btnBressenham;
    private javax.swing.JToggleButton btnBrush;
    private javax.swing.JToggleButton btnColorPicker;
    private javax.swing.JToggleButton btnFloodFill;
    private javax.swing.JToggleButton btnLineDDA;
    private javax.swing.JToggleButton btnMidpointCircle;
    private javax.swing.JToggleButton btnMidpointEllipse;
    private javax.swing.JToggleButton btnRectangle;
    public javax.swing.JPanel canvas;
    public javax.swing.JComboBox cmbFillStyle;
    public javax.swing.JComboBox cmbLineStyle;
    public javax.swing.JPanel color1;
    private javax.swing.JPanel color1Wrapper;
    public javax.swing.JPanel color2;
    private javax.swing.JPanel color2Wrapper;
    private javax.swing.JPanel colorPane;
    private javax.swing.JPanel containerPane;
    private javax.swing.JPanel fillStylePane;
    private javax.swing.JLabel lbCopyright;
    private javax.swing.JLabel lbCursor;
    private javax.swing.JLabel lbCursorPosition;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbEndPosition;
    private javax.swing.JLabel lbStart;
    private javax.swing.JLabel lbStartPosition;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblColor2;
    private javax.swing.JPanel lineStylePane;
    private javax.swing.JPanel mainPane;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuPrint;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSaveAs;
    private javax.swing.JPanel pixelPane;
    public javax.swing.JSlider pixelSlider;
    private javax.swing.ButtonGroup shapeButtonGroup;
    private javax.swing.JPanel shapePane;
    private javax.swing.JPanel sidePane;
    // End of variables declaration//GEN-END:variables
}
